# Generated by Django 2.0 on 2017-12-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('duedate', models.DateField(blank=True, null=True, verbose_name='Due Date')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('severity', models.CharField(blank=True, choices=[('Trivial', 'Trivial'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical'), ('Blocker', 'Blocker')], max_length=16, null=True, verbose_name='Severity')),
                ('state', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Blocked', 'Blocked'), ('Merged', 'Merged'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=16, verbose_name='State')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickettracker.Milestone', verbose_name='Milestone')),
                ('other_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickettracker.Ticket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickettracker.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('body', models.CharField(max_length=1000, verbose_name='Body')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
