# Generated by Django 2.0 on 2017-12-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickettracker', '0003_auto_20171224_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='other_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related', to='tickettracker.Ticket'),
        ),
    ]
