# Generated by Django 2.0 on 2017-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickettracker', '0005_auto_20171225_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(1, 'Blocker'), (2, 'Critical'), (3, 'Major'), (4, 'Minor'), (5, 'Trivial')], null=True, verbose_name='Severity'),
        ),
    ]
