# Generated by Django 2.0 on 2017-12-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickettracker', '0006_auto_20171229_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlogentry',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tickettracker.Ticket', verbose_name='Ticket'),
            preserve_default=False,
        ),
    ]
